version: '2'

services:
  base-workspace:
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /host/data:/var/consul                       # volume for data
    environment:
      - CONSUL_VERSION=${CONSUL_VERSION}
      - CONSULUI_VERSION=${CONSULUI_VERSION}
      - CONSULTEMPLATE_VERSION=${CONSULTEMPLATE_VERSION}
      - RUBY_VERSION=${RUBY_VERSION}

